### ISSUE TITLE
everest-core README prerequisite package install error

### ISSUE THREAD

**Issue by GoGerrish** [EVerest/EVerest-archived#108]
Reference: https://github.com/EVerest/everest-core#prerequisites

I am using Linux Mint 20 (Ubuntu 20.04).

The install instruction fails because NPM and nodejs have unmet dependencies
`sudo apt install -y python3-pip git rsync wget cmake doxygen graphviz build-essential clang-tidy cppcheck openjdk-17-jdk npm docker docker-compose libboost-all-dev nodejs libssl-dev libsqlite3-dev clang-format curl rfkill libpcap-dev libevent-dev pkg-config`

I get the follow message and I cannot resolve (I also tested on a Debian laptop and get the same message and could not resolve):

> The following packages have unmet dependencies.
>  nodejs : Conflicts: npm
>  npm : Depends: node-gyp (>= 3.6.2~) but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

My node version is v20.5.1
My npm version is 9.8.0

A further package conflict error is encountered here:
`python3 -m pip install --upgrade pip setuptools wheel jstyleson jsonschema
`
I get this error message:

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> icetea 1.2.4 requires jsonschema<3.0.0, but you have jsonschema 4.19.1 which is incompatible.
> icetea 1.2.4 requires prettytable<1.0, but you have prettytable 2.5.0 which is incompatible.
>

**Comment by krealyt** [comment]
For the first topic, just a quick try. Have you already looked into that?
https://stackoverflow.com/questions/55464934/npm-depends-node-gyp-3-6-2-but-it-is-not-going-to-be-installed

**Comment by GoGerrish** [comment]
> For the first topic, just a quick try. Have you already looked into that? https://stackoverflow.com/questions/55464934/npm-depends-node-gyp-3-6-2-but-it-is-not-going-to-be-installed

It did not work for me. 

I've switched to using a Raspberry Pi 4 and have made better headway. It's worth noting that on the Raspberry Pi 4, clang12 is not available, but clang13 and associated tools are available.

However, I have got stuck with this README instruction as the directory "Josev" does not exist:

`cd ~/checkout/everest-workspace/Josev
`

**Comment by krealyt** [comment]
@GoGerrish Just realized that this issue has been discussed on the mailing list. Do you have open questions regarding this one or has it been solved?

**Comment by GoGerrish** [comment]
It has been solved. Thanks.

PS. I upgraded my laptop to Ubuntu 22.04 and the install process worked a charm. 
PPS. What can slow the install process down though, is if you use a pass phrase with SSH. Asks for it to be entered too many times.
