### ISSUE TITLE
CI GTest version is breaking tests

### ISSUE THREAD

**Issue by ghost** [EVerest/EVerest-archived#137]
**Describe the bug**

When running test in CI test would fail for unexplained reasons after passing locally.

**To Reproduce**
1. Go to https://github.com/EVerest/libocpp/actions/runs/7790633039
3. Click on ctest-report under Artifacts Produced during runtime
4. Unzip the archive and open the test report in a text editor.
5. See all new ChargepointTestFixture test failing. 

**Expected behavior**
The CI and local development should match in test execution. Dependencies should be set with CMake/EDM and not rely on OS level repos.

**Desktop (please complete the following information):**
 - Debian 12 within a devcontainer.
 - Host is M2 iOS.

**Additional context**
There are a couple issues with the CI images here https://github.com/EVerest/everest-ci

The alpine version cannot be built locally. It is failing with python issues:

> Building wheel for cffi (pyproject.toml) did not run successfully.
...
error: command '/usr/bin/gcc' failed with exit code 1
13.64       [end of output]
13.64
13.64   note: This error originates from a subprocess, and is likely not a problem with pip.
13.64   ERROR: Failed building wheel for cffi
13.64 ERROR: Could not build wheels for cffi, which is required to install pyproject.toml-based projects

I cannot find a work around with this case and could not specifically test alpine which is what run in CI.

Are there any suggestion on how to build the alpine version locally? Building in alpine has usually been a pain point. It is better suited as a runner than a builder.

I was able to rebuild the Debian based image and test the run locally inside the container. The issue with Debian (and I suspect alpine) was the version of GTest being pulled in from the repo. In my local devcontainer running Debian 12 I get version 1.12.1 in the CI Debian 11.7-slim GTest is 1.10. 

I was able to confirm updating the version of Debian in the CI container would successfully run the tests.

Likewise, removing [line](https://github.com/EVerest/everest-ci/blob/ea4a417ec6c86fe58784b2a14921a3df1c8aab06/docker/images/build-kit/debian.Dockerfile#L29C1-L29C23) and setting GTest in the `dependencies.yaml` file partially works. 

There appears to be some oddity with EDM. When used I have to run CMake without BUILD_TESTING and run ninja install. After that I am able to rerun CMake with BUILD_TESTING and run the tests. I am unclear as to the cause of this behavior.

**Comment by andistorm** [comment]
Thanks for reporting this issue!

Could you try to split this up in multiple issues?
For me it is not 100% clear which setup has an issue and what the main pain point here is.

If I am right there are multiple issues:
1) Wrong GTest version in Alpine/Debian build-kit image
2) Alpine build-kit is not buildable locally
3) GTest should be included by EDM not by build-kit Dockerfile
4) Issue with BUILD_TESTING flag 

Not sure if this split would fit your issues here, but for at least me splitting up the issue would it make more clear to me what the actual problem is and how we can work on that.

**Comment by ghost** [comment]
@andistorm your analysis is correct. I will break them out. I didn't want to spam too many at one time.

**Comment by ghost** [comment]
Created separate smaller issues
https://github.com/EVerest/EVerest/issues/139
https://github.com/EVerest/EVerest/issues/140
https://github.com/EVerest/EVerest/issues/141
