### ISSUE TITLE
libmodbus recipe name collides with existing recipe from meta-oe

### ISSUE THREAD

**Issue by DR-CompleoCS** [EVerest/EVerest-archived#151]
**Describe the bug**
In meta-everest (kirkstone) there is the recipe libmodbus_0.3.1. In meta-oe there is the recipe libmodbus_3.1.7.

So we have a conflict here.

If there is software in addition to EVerest that requires the libmodbus version 3.1.7 from meta-oe, a build is no longer possible.

Suggestion: Rename the library e.g. to libmodbus-everest

**To Reproduce**
1. have a distroconfig with 'PREFERRED_VERSION_libmodbus = "3.7.1"' which uses the library from meta-oe.
2. add meta-everest
3. execute bitbake
4. see CMAKE error in libsunspec

**Expected behavior**
The build should run without errors

**Comment by hikinggrass** [comment]
This has been fixed in the[ kirkstone branch for 2024.3.0-rc2](https://github.com/EVerest/meta-everest/tree/release/kirkstone/2024.3.0-rc2) and will end up in the upcoming release as well
