### ISSUE TITLE
Can I run libocpp standalone on ESP32?

### ISSUE THREAD

**Issue by JeetVdevve** [EVerest/EVerest-archived#153]
**Describe the bug**
I have ESP32 Microcontroller, and I want to run libocpp library on it. Can I port the library to microcontroller or do I have run Linux on it to make it run? I tried to import the libocpp files like "charger_point.cpp" into the firmware but it throws error of modules not found

**Comment by krealyt** [comment]
That question has also been asked in the EVerest Zulip channels:
https://lfenergy.zulipchat.com/#narrow/stream/417673-general/topic/How.20to.20setup.20with.20ESP32.3F
