### ISSUE TITLE
Does EVerest support the STM32 platform?

### ISSUE THREAD

**Issue by zhenbin-lin** [EVerest/EVerest-archived#165]
Does modules support simple and easy to be used in embedded MCU platforms such as STM32 or NXP?

**Comment by krealyt** [comment]
Besides the open-source software EVerest, there is also an open-hardware project available.

See here, a Yeti STM32 firmware: https://github.com/PionixPublic/yeti-firmware

That is tested regularly with EVerest.

I found also positive feedback about some NXP MCUs like i.MX6 / i.MX8 or i.MX 93.

As I am no hardware guy, it would probably be a great idea to reach out to a broader community and visit the Zulip EVerest channels here: https://lfenergy.zulipchat.com/ - there are already some discussions about MCUs in use.
