### ISSUE TITLE
Unable to build HTML documentation

### ISSUE THREAD

**Issue by lategoodbye** [EVerest/EVerest-archived#193]
**Describe the bug**
I tried to build the HTML documentation from this repository on my Ubuntu 22.04 with Sphinx, but i'm getting the following error:

````
$ make html

Sphinx v7.3.7 in Verwendung

Exception occurred:

  File "/home/stefan/git/EVerest/docs/_ext/staticpages/extension.py", line 313, in setup

    from sphinx.builders.html import setup_js_tag_helper

ImportError: cannot import name 'setup_js_tag_helper' from 'sphinx.builders.html' (/home/stefan/.local/lib/python3.10/site-packages/sphinx/builders/html/__init__.py)

The full traceback has been saved in /tmp/sphinx-err-a_lm8kxz.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
````

**To Reproduce**
1. git clone https://github.com/EVerest/EVerest.git
2. cd EVerest/docs
4. pip install sphinxcontrib-contentui
5. pip install sphinxcontrib-svg2pdfconverter
6. pip install sphinx-notfound-page
7. make html

**Expected behavior**
Sphinx should build the HTML documentation.

**Desktop (please complete the following information):**
- Ubuntu 22.04
- Sphinx v7.3.7
- Python version: 3.10.12
- Jinja2 version: 3.1.2

**Comment by andistorm** [comment]
The sphinx version you use is currently not supported. The newest version that is supported is `v7.1.2`

If you have installed with sphinx you can downgrade with:

``` bash
pip install sphinx==7.1.2
```

**Comment by andistorm** [comment]
FYI: If you want to build the full documentation you need to do more than running make html, best probably would be to orientate at the workflow that is used by the CI:

https://github.com/EVerest/EVerest/blob/main/.github/workflows/deploy-everest-doc.yml#L145-227

**Comment by lategoodbye** [comment]
Thanks
