### ISSUE TITLE
Issue EVerest CORE installation

### ISSUE THREAD

**Issue by AndyChriss123** [EVerest/EVerest-archived#21]
Hello. Could you please help me with this issue that I'm having?
While attempting to install EVerest CORE, while following the guide in the README file, after downloading the repository and installing the EDM:  

cd everest-dev-environment/dependency_manager
python3 -m pip install .

when I attempt to setup the Workspace:

edm --register-cmake-module --config ../everest-complete.yaml --workspace ~/checkout/everest-workspace

I get an error saying that there is no such command known as "edm"

edm --register-cmake-module --config ../everest-complete.yaml --workspace ~/checkout/everest-workspace

Is there something that I'm missing as I'm new to linux and github and maybe you could give me some guidance if you ever find the time?
I understand that it might not be the case as this project is very complex and in the early stages and you have a lot of things to do aside from helping noob here but still... I tought I'd ask.
Thank you very much for your effort, can't wait to see it 100% up and running!

**Comment by hikinggrass** [comment]
What kind of linux distribution are you running and what's the output whilst installing edm with:
```bash
 python3 -m pip install .
```
?

There might be an issue that python packages are installed into a directory that's not in your PATH which you could rectify by adding this directory in your bashrc/bash_profile file

**Comment by AndyChriss123** [comment]
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

As for the output, this is the last part of it soooo yeah... orange=white and only red=bad where i come from so if this fixes my problem it seems it was a noob issue indeed:

  WARNING: The script edm is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

Thank you very much for taking the time to help me out!
There are many things that I know well.. but this is all new to me so I really appreciate the effort.
I will close this issue ASAP if the problem is gone.

**Comment by hikinggrass** [comment]
It could actually be a bit easier on a raspberry pi, since the path should already be set in /home/pi/.profile it's just behind a check that will have validated to false before you installed edm. In this case a simple logout & login might already do the trick. Otherwise just add the following line to your /home/pi/.profile file:

```bash
PATH=$PATH:/home/pi/.local/bin
```

**Comment by AndyChriss123** [comment]
Thank you! All is well now.
For some reason I had to add the path manually. It's a VM so maybe that is why.
When I get to the simulator part if I encounter more issues I might have to appeal again but hopefully not. You respond so fast people will think you got nothing better to do than help noobs around here :)
Super grateful, thanks again!
