### ISSUE TITLE
ISSUE with deploying simulator

### ISSUE THREAD

**Issue by AndyChriss123** [EVerest/EVerest-archived#22]
Hello! Thank you for the last time as you were very fast and kind enough to answer me in the first place. I'm rather new to Linux so I don't really know if these are basic things to troubleshoot or not, so if I ever am a bother to you please let me know so I can do better in the future.
At this point everything works except the simulator, I managed to install EVerest, launch the Docker Container and configure it but when I try to initiate the simulator from everest-core/build/ with **.././run_sil.sh** I get this error:
```
 pi@raspberry:~/checkout/everest-workspace/everest-core/build $ .././run_sil.sh
.././run_sil.sh: line 5: dist/bin/manager: No such file or directory
```
Do you have any idea what could be the case for this?
After I get the simulator running and I can play with it I'm sure I won't have to bother you for a while, you get at least a couple of weeks without me mumbling I promise :)

**Comment by AndyChriss123** [comment]
Also, I forgot to add my OS info:

```
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by hikinggrass** [comment]
Did you run
```bash
make install
```
In the build folder before trying the execute the run_sil.sh script?

**Comment by AndyChriss123** [comment]
My terminal now has many colors all over it yes, for that I thank you, it is very beautiful.
It should take a while for the process to complete as I haven't set the number of CPUs it can use but something is happening and I'm happy. I will close this issue if this solves my problem.
Thank you very much!
Enjoy until we meet again... hopefully I won't be having any more disappointing questions by then!

**Comment by AndyChriss123** [comment]
```
[ 26%] Building CXX object _deps/everest-framework-build/everestjs/CMakeFiles/everestjs.dir/everestjs.cpp.o
/home/pi/checkout/everest-workspace/everest-framework/everestjs/everestjs.cpp:8:10: fatal error: napi.h: No such file or directory
 #include <napi.h>
          ^~~~~~~~
compilation terminated.
make[2]: *** [_deps/everest-framework-build/everestjs/CMakeFiles/everestjs.dir/build.make:63: _deps/everest-framework-build/everestjs/CMakeFiles/everestjs.dir/everestjs.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2452: _deps/everest-framework-build/everestjs/CMakeFiles/everestjs.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
Soo.. this happened while I was staring at the RGB...

**Comment by a-w50** [comment]
Hi Andy,

do you have nodejs installed?

**Comment by hikinggrass** [comment]
At first glance that looks like you might have an (too) old version of nodejs, what kind of version are you running? It would probably be best to update it to 12 or 14+

**Comment by AndyChriss123** [comment]
Hello and thanks.
I have nodejs version 18 installed using NVM as I could not get it to install normally. My default sources give me a very outdated version 10.x.x and I couldn't install the latest version using the CURL method. the CURL command has done it's job apparently and the version is listed with **sudo apt list nodejs** but whenever I install it I get the old version, so I found NVM which seemed to have solved my issue somehow but do you think that is a problem?
At this point, if it is a nodejs problem i will do my best to solve it on my own as I don't want to waste too much of your time..
I feel apologetic as this section is entitled issues for EVerest but so far it is just me not knowing much about linux infrastructure let's say..
