### ISSUE TITLE
Failure:  Weekly Lint repository

### ISSUE THREAD

**Issue by andistorm** [EVerest/EVerest-archived#26]
**Describe the bug**
The workflow `Weekly Lint repository` throws errors, which means that the repository is  probably not conform, see [here](https://github.com/EVerest/EVerest/actions/runs/2683936521) for example

**To Reproduce**
1. Trigger the workflow
2. See result

**Expected behavior**
The workflow shouldn't fail in case of a conform repository

**Comment by Fufanu** [comment]
Fixed the error the Linter has thrown in the README.md. A section for Licensing was missing.
