### ISSUE TITLE
Failure: Send TSC meeting agenda to email list

### ISSUE THREAD

**Issue by andistorm** [EVerest/EVerest-archived#27]
**Describe the bug**
The workflow `Send TSC meeting agenda to email list` doesn't fail, but it doesn't send any email, because there isn't selected any email list. See [here](https://github.com/EVerest/EVerest/actions/runs/2698197336) and [here](https://github.com/EVerest/EVerest/actions/runs/2698197336/workflow).

**To Reproduce**
1. Create an issue
2. Wait for completion

**Expected behavior**
Receiving an email after workflow completion

**Comment by Fufanu** [comment]
@andistorm 
We can close this bug as we do not need this workflow anymore. Can you remove it and close this issue?
