### ISSUE TITLE
Create Agenda workflow doesn't start

### ISSUE THREAD

**Issue by andistorm** [EVerest/EVerest-archived#28]
**Describe the bug**
The workflow `.github/workflows/create_agenda.yml` doesn't start, reason for this is something in the workflow file, see [here](https://github.com/EVerest/EVerest/actions/runs/2698081814).

**To Reproduce**
1. Trigger workflow with `Run workflow` [here](https://github.com/EVerest/EVerest/actions/workflows/create_agenda.yml)

**Expected behavior**
Workflow starts..

**Comment by Fufanu** [comment]
@andistorm 
We can close this bug as we do not need this workflow anymore. Can you remove it and close this issue?
