### ISSUE TITLE
Everest Simulation on imx6ul Platform

### ISSUE THREAD

**Issue by KodRider** [EVerest/EVerest-archived#50]
I have built EVerest code on imx6ul platform running Debian: Bullseye 11, Linux Kernel
uname -r => 5.4.142-g5227ff0e2a5c

When I want to run the simulation containers through /everest-utils/docker/ directory via "docker-compose up -d" I realized that the simulation containers are built for INTEL platform and they can not be run on imx6ul.

Questions / Suggestions :
1- Is there a way of doing this simulation fully on imx6ul-dart platform, do you have those containers/images built already ?
2- Is it possible to run the simulation containers in the INTEL PC platform and communicate EVerest code running on imx6ul ?

**Comment by KodRider** [comment]
I realized that I had to use 32 bit versions of MariaDB and Maven :

I have done the changes below and the problem solved :

  File-1 : ~/checkout/everest-workspace/everest-utils/docker/docker-compose.yml
  	         "**image: mariadb:10.4**" into "**image: lscr.io/linuxserver/mariadb:latest**"

  File-2 : ~/checkout/everest-workspace/everest-utils/docker/steve/Dockerfile
	         "**FROM maven:3.6.1-jdk-11**" line changed into "**FROM maven:3.8.1-adoptopenjdk-11**"
	         "**RUN apt-get update && apt-get install -y wget**" line added before "**RUN wget**" line
                 "**amd64**" to "**armhf**"

The links below led me to the solution, thanx to the authors :

     https://hub.docker.com/r/linuxserver/mariadb
     https://github.com/steve-community/steve/issues/630
     https://github.com/steve-community/steve/issues/631

**Comment by KodRider** [comment]
Closing the issue

**Comment by a-w50** [comment]
Thanks for sharing your solution.  When creating the docker container, we didn't had in mind, that it could be run on an embedded platform.  If docker has good support for defining multi-platform containers, this might be a good enhancement
