### ISSUE TITLE
Display SUPPORT for Yetti+Yak

### ISSUE THREAD

**Issue by AndyChriss123** [EVerest/EVerest-archived#56]
Hello and thank you very much for attending to these questions/issues. You are always very helpful.
What options do I have for interfacing a display module to the Yak board?
I'm mostly interested in ways of interfacing commercially available modules with display and touch inputs.
I am unaware of what you custom connector is called and whether if there is anything that would connect to it on the market.
As I see it right now, I'm limited to using the SPI connection on the Yetti which is very limiting in terms of available hardware with proper required performance, or interfacing some I2C module to the Yak board which seems a bit roundabout.
Am I limited to these options or is there some other option available that I am unaware of?
Thank you for your time!

**Comment by AndyChriss123** [comment]
Can I for example use a HDMI to Micro USB adapter for the video signal?

**Comment by corneliusclaussen** [comment]
The proprietary connector has HDMI signals, one USB for touch controller as well as 5V power supply for the display all in one connector. You can order displays that fit from Pionix that mount directly on the Yak. They are 5", 1000 nits daylight readable, capacitive touch. If you want to connect another display you can always change the schematics to e.g. a mini HDMI if you like. Or you build yourself an adapter for the proprietary connector.

**Comment by AndyChriss123** [comment]
Thank you very much!
A custom adapter is what we will go with for now. We will contact you for an order if we run in to any trouble.
