### ISSUE TITLE
Everest-Core Build Error

### ISSUE THREAD

**Issue by ffatihozen** [EVerest/EVerest-archived#68]
Hello,

I use Ubuntu 20.04 , am trying to build it. 

I saw an error while using edm. When I enter this command : edm --register-cmake-module
It gives this:
`usage: edm [-h] [--version] [--workspace WORKSPACE] [--working_dir WORKINGDIR] [--out OUTFILENAME] [--include_deps] [--config CONFIG]
           [--create-vscode-workspace] [--cmake] [--verbose] [--nocolor] [--install-bash-completion] [--create-config CREATECONFIG]
           [--external-in-config] [--include-remotes [INTERNAL [INTERNAL ...]]] [--create-snapshot [CREATE_SNAPSHOT]] [--git-info]
           [--git-fetch] [--git-pull [GIT_PULL [GIT_PULL ...]]]
           {init,list,rm,git,snapshot} ...
edm: error: unrecognized arguments: --register-cmake-module
`

My node version is v12.22.12. I have tried it with newer ones. My npm version is 6.14.16.

'Found nodejs version 'v12.22.12' that can provide Node-API version '8' which satifies the requirement of Node-API version '6''

I get a notification with cmake .. command as above. Maybe this can give a clue to solve my problem.

I face an error as below.
 
`Scanning dependencies of target everestjs
[ 88%] Building CXX object _deps/everest-framework-build/everestjs/CMakeFiles/everestjs.dir/everestjs.cpp.o
[ 88%] Building CXX object _deps/libocpp-build/lib/CMakeFiles/ocpp.dir/ocpp/v201/messages/SendLocalList.cpp.o
[ 89%] Building CXX object _deps/libocpp-build/lib/CMakeFiles/ocpp.dir/ocpp/v201/messages/SetChargingProfile.cpp.o
[ 89%] Building CXX object _deps/libocpp-build/lib/CMakeFiles/ocpp.dir/ocpp/v201/messages/SetDisplayMessage.cpp.o
[ 89%] Linking CXX executable Store/Store
[ 89%] Built target Store
Scanning dependencies of target everestpy
[ 89%] Building CXX object _deps/everest-framework-build/everestpy/CMakeFiles/everestpy.dir/everestpy.cpp.o
In file included from /home/fatihozen/checkout/everest-workspace/everest-core/build/node_modules/node-addon-api/napi.h:3189,
                 from /home/fatihozen/checkout/everest-workspace/everest-framework/everestjs/everestjs.cpp:9:
/home/fatihozen/checkout/everest-workspace/everest-core/build/node_modules/node-addon-api/napi-inl.h: In member function ‘T* Napi::Env::GetInstanceData() const’:
/home/fatihozen/checkout/everest-workspace/everest-core/build/node_modules/node-addon-api/napi-inl.h:558:24: error: there are no arguments to ‘napi_get_instance_data’ that depend on a template parameter, so a declaration of ‘napi_get_instance_data’ must be available [-fpermissive]
  558 |   napi_status status = napi_get_instance_data(_env, &data);
      |                        ^~~~~~~~~~~~~~~~~~~~~~
/home/fatihozen/checkout/everest-workspace/everest-core/build/node_modules/node-addon-api/napi-inl.h:558:24: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/fatihozen/checkout/everest-workspace/everest-core/build/node_modules/node-addon-api/napi-inl.h: In static member function ‘static Napi::BigInt Napi::BigInt::New(napi_env, int64_t)’:
/home/fatihozen/checkout/everest-workspace/everest-core/build/node_modules/node-addon-api/napi-inl.h:900:24: error: ‘napi_create_bigint_int64’ was not declared in this scope; did you mean ‘napi_create_int64’?
  900 |   napi_status status = napi_create_bigint_int64(env, val, &value);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~
      |                        napi_create_int64
/home/fatihozen/checkout/everest-workspace/everest-core/build/node_modules/node-addon-api/napi-inl.h: In static member function ‘static Napi::BigInt Napi::BigInt::New(napi_env, uint64_t)’:
/home/fatihozen/checkout/everest-workspace/everest-core/build/node_modules/node-addon-api/napi-inl.h:907:24: error: ‘napi_create_bigint_uint64’ was not declared in this scope; did you mean ‘napi_create_string_utf16’?
  907 |   napi_status status = napi_create_bigint_uint64(env, val, &value);
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                        napi_create_string_utf16
/home/fatihozen/checkout/everest-workspace/everest-core/build/node_modules/node-addon-api/napi-inl.h: In static member function ‘static Napi::BigInt Napi::BigInt::New(napi_env, int, size_t, const uint64_t*)’:
/home/fatihozen/checkout/everest-workspace/everest-core/build/node_modules/node-addon-api/napi-inl.h:918:7: error: ‘napi_create_bigint_words’ was not declared in this scope; did you mean ‘napi_create_async_work’?
  918 |       napi_create_bigint_words(env, sign_bit, word_count, words, &value);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~
      |       napi_create_async_work
/home/fatihozen/checkout/everest-workspace/everest-core/build/node_modules/node-addon-api/napi-inl.h: In member function ‘int64_t Napi::BigInt::Int64Value(bool*) const’:
/home/fatihozen/checkout/everest-workspace/everest-core/build/node_modules/node-addon-api/napi-inl.h:940:7: error: ‘napi_get_value_bigint_int64’ was not declared in this scope; did you mean ‘napi_get_value_int64’?
  940 |       napi_get_value_bigint_int64(_env, _value, &result, lossless);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       napi_get_value_int64
/home/fatihozen/checkout/everest-workspace/everest-core/build/node_modules/node-addon-api/napi-inl.h: In member function ‘uint64_t Napi::BigInt::Uint64Value(bool*) const’:
/home/fatihozen/checkout/everest-workspace/everest-core/build/node_modules/node-addon-api/napi-inl.h:948:7: error: ‘napi_get_value_bigint_uint64’ was not declared in this scope; did you mean ‘napi_get_value_string_utf16’?
  948 |       napi_get_value_bigint_uint64(_env, _value, &result, lossless);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       napi_get_value_string_utf16
/home/fatihozen/checkout/everest-workspace/everest-core/build/node_modules/node-addon-api/napi-inl.h: In member function ‘size_t Napi::BigInt::WordCount() const’:
/home/fatihozen/checkout/everest-workspace/everest-core/build/node_modules/node-addon-api/napi-inl.h:956:7: error: ‘napi_get_value_bigint_words’ was not declared in this scope; did you mean ‘napi_get_value_string_utf16’?
  956 |       napi_get_value_bigint_words(_env, _value, nullptr, &word_count, nullptr);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       napi_get_value_string_utf16
/home/fatihozen/checkout/everest-workspace/everest-core/build/node_modules/node-addon-api/napi-inl.h: In member function ‘void Napi::BigInt::ToWords(int*, size_t*, uint64_t*)’:
/home/fatihozen/checkout/everest-workspace/everest-core/build/node_modules/node-addon-api/napi-inl.h:965:7: error: ‘napi_get_value_bigint_words’ was not declared in this scope; did you mean ‘napi_get_value_string_utf16’?
  965 |       napi_get_value_bigint_words(_env, _value, sign_bit, word_count, words);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       napi_get_value_string_utf16
[ 89%] Building CXX object _deps/libocpp-build/lib/CMakeFiles/ocpp.dir/ocpp/v201/messages/SetMonitoringBase.cpp.o
`

**Comment by krealyt** [comment]
Sorry for the late response. The parameter --register-cmake-module is obsolete. You can follow the official Quick Start Guide from EVerest here: https://everest.github.io/nightly/general/02_quick_start_guide.html

We will change all other pages that still show this parameter.

Please see if the Quick Start Guide and a current release of EVerest also solves your other error. If still having problems, reach out here via GitHub anytime.
