### ISSUE TITLE
Use libocpp in a project

### ISSUE THREAD

**Issue by ziyadtarek7** [EVerest/EVerest-archived#94]
Hello,

I want to use libocpp in a project that i'm working on, I built everest-core and libocpp but I can't figure out how to include it in my project.
I tried including charge_point.hpp but I get include errors from all the header files in the library that they couldn't be found although they are added to my compiler include_path,

I would appreciate any guidance

**Comment by hikinggrass** [comment]
Hi,

you can find an example how to build libocpp with cmake+FetchContent here: https://github.com/EVerest/libocpp/blob/main/doc/build-with-fetchcontent/CMakeLists.txt

To link against it in your code it should be enough to add everest::ocpp to your target link libraries like the OCPP module in everest-core (https://github.com/EVerest/everest-core/blob/main/modules/OCPP/CMakeLists.txt):
```cmake
target_link_libraries(your_target_name
    PRIVATE
        everest::ocpp
        OpenSSL::SSL
        OpenSSL::Crypto
)
```

I hope this helps

**Comment by ziyadtarek7** [comment]
> Hi,
> 
> you can find an example how to build libocpp with cmake+FetchContent here: https://github.com/EVerest/libocpp/blob/main/doc/build-with-fetchcontent/CMakeLists.txt
> 
> To link against it in your code it should be enough to add everest::ocpp to your target link libraries like the OCPP module in everest-core (https://github.com/EVerest/everest-core/blob/main/modules/OCPP/CMakeLists.txt):
> 
> ```cmake
> target_link_libraries(your_target_name
>     PRIVATE
>         everest::ocpp
>         OpenSSL::SSL
>         OpenSSL::Crypto
> )
> ```
> 
> I hope this helps

Yes, this helped a lot, thank you!
